--------------------------------------------------------
--  File created - Cumartesi-Mayýs-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APRIORI
--------------------------------------------------------

  CREATE TABLE "SUKRIYE"."APRIORI" 
   (	"ID" NUMBER, 
	"URUN1" VARCHAR2(100 BYTE), 
	"URUN2" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SUKRIYE.APRIORI
SET DEFINE OFF;
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('1','HOME BUILDING BLOCK WORD','LOVE BUILDING BLOCK WORD');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('1','PINK CREAM FELT CRAFT TRINKET BOX ','SET OF 3 CAKE TINS PANTRY DESIGN ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','ALARM CLOCK BAKELIKE PINK','ALARM CLOCK BAKELIKE GREEN');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','ALARM CLOCK BAKELIKE GREEN','ALARM CLOCK BAKELIKE RED ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','ALARM CLOCK BAKELIKE PINK','ALARM CLOCK BAKELIKE RED ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','SET/6 RED SPOTTY PAPER CUPS','SET/20 RED RETROSPOT PAPER NAPKINS ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','SET/6 RED SPOTTY PAPER PLATES','SET/20 RED RETROSPOT PAPER NAPKINS ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','SET/6 RED SPOTTY PAPER CUPS','SET/6 RED SPOTTY PAPER PLATES');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','ALARM CLOCK BAKELIKE GREEN','POSTAGE');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','ALARM CLOCK BAKELIKE PINK','POSTAGE');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','SET/6 RED SPOTTY PAPER CUPS','POSTAGE');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('2','POSTAGE','SET/6 RED SPOTTY PAPER PLATES');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('3','BLUE STRIPE CERAMIC DRAWER KNOB','RED STRIPE CERAMIC DRAWER KNOB');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('4','CHARLOTTE BAG PINK POLKADOT','CHARLOTTE BAG SUKI DESIGN');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('4','KEY FOB , SHED','KEY FOB , BACK DOOR ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('4','RED RETROSPOT PICNIC BAG','TOILET SIGN OCCUPIED OR VACANT');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('4','SUKI  SHOULDER BAG','SKULL SHOULDER BAG');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','CHRISTMAS CRAFT WHITE FAIRY ','CHRISTMAS CRAFT TREE TOP ANGEL');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','CHRISTMAS CRAFT TREE TOP ANGEL','GARDENERS KNEELING PAD CUP OF TEA ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','ROTATING SILVER ANGELS T-LIGHT HLDR','CHRISTMAS CRAFT TREE TOP ANGEL');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','CHRISTMAS CRAFT WHITE FAIRY ','GARDENERS KNEELING PAD CUP OF TEA ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','ROTATING SILVER ANGELS T-LIGHT HLDR','CHRISTMAS CRAFT WHITE FAIRY ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','DOORMAT FANCY FONT HOME SWEET HOME','IVORY KITCHEN SCALES');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','ROTATING SILVER ANGELS T-LIGHT HLDR','GARDENERS KNEELING PAD CUP OF TEA ');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','PAPER CHAIN KIT VINTAGE CHRISTMAS','PACK OF 6 BIRDY GIFT TAGS');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','PACK OF 6 BIRDY GIFT TAGS','SET OF 20 VINTAGE CHRISTMAS NAPKINS');
Insert into SUKRIYE.APRIORI (ID,URUN1,URUN2) values ('5','PAPER CHAIN KIT VINTAGE CHRISTMAS','SET OF 20 VINTAGE CHRISTMAS NAPKINS');
--------------------------------------------------------
--  Ref Constraints for Table APRIORI
--------------------------------------------------------

  ALTER TABLE "SUKRIYE"."APRIORI" ADD CONSTRAINT "APRIORI_MUSTERILER_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SUKRIYE"."MUSTERILER" ("ID") ENABLE;
